spring:
  application:
    name: 07_Cloud_Config_Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NaveenKumarJadi/configuration_properties.git
          
server:
  port: 9093  